[package]
name = "tx_engine"
version = "0.1.0"
edition = "2021"

[dependencies]

csv = "1.3"
tokio = { version = "1.42", features = ["sync", "rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
